version: '3'

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html/helpdesk/
    depends_on:
      - mysql
    networks:
      - helpdesk-network

  nginx:
    build: ./nginx
    volumes:
      - ./:/var/www/html/helpdesk/
    ports:
      - "80:80"
    networks:
      - helpdesk-network

  mysql:
    image: mysql:5.7
    container_name: helpdesk-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=helpdesk
    networks:
      - helpdesk-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  helpdesk-network:
    driver: bridge
